### ISSUE TITLE
Bug: neovim instance does not resize itself automatically

### ISSUE THREAD

**Issue by antonk52** [ThePrimeagen/vim-be-good#102]
When resizing the terminal/tmux-pane the neovim instance hangs before adopting to the new size. The resize happens after a press of a any key inside the neovim instance

The bug is consistently reproducable on macos 10.14.6 in neovim v0.4.4. I've also tested it in vim v8.2 where the behavior differs, the vim seems to update with a delay 1~2s.

vimrc to reproduce
```vim
set nocompatible
filetype off

" load vim plug if it is not installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'ThePrimeagen/vim-be-good', {'do': './install.sh'}
call plug#end()

filetype plugin indent on
syntax enable

set laststatus=2
```

Here's what it looks like

![bug](https://user-images.githubusercontent.com/5817809/92336759-bb8f6700-f0ac-11ea-9c30-4a07f3b379f7.gif)

to avoid the current behavior I had to disable the plugin which means I can no longer improve my vim speed 😭

**Comment by bryall** [comment]
per the Install section on the README.  VImBeGood requires the master branch of Neovim (version 0.5). the hanging is probably being caused by a function not present on 0.4.4 Neovim.
