### ISSUE TITLE
E492: Not an editor command

### ISSUE THREAD

**Issue by FedeCuci** [ThePrimeagen/vim-be-good#13]
Whenever I try to run `:VimBeGood` in an empty file (or any file at all) in vim, I get an error saying:
`E492: Not an editor command`.

I am running NeoVim version 0.4.3 and installed the plugin using VimPlug.

I followed the installation procedure in the README.md and restarted my terminal a few times. Anyone knows how to solve this?

**Comment by gsihaj5** [comment]
got same error can't tell what to do

**Comment by ThePrimeagen** [comment]
Really?  That is unfortunate, sorry about that.

Just want to make sure you execute `:Up` or `:UpdateRemotePlugins` (same command, one is shorthand).

**Comment by FedeCuci** [comment]
@ThePrimeagen I was able to fix the issue. When executing `:Up` I got an error along the lines of: `cannot find the neovim node package`. This was the problem. I solved it by running `npm install -g neovim` ([Found here](https://github.com/neovim/node-client/issues/55)). Now running :`Up` again works without errors and after restarting the terminal the game works. 

@gsihaj5 Hopefully this works for you too.

**Comment by plouto5** [comment]
> @ThePrimeagen I was able to fix the issue. When executing `:Up` I got an error along the lines of: `cannot find the neovim node package`. This was the problem. I solved it by running `npm install -g neovim` ([Found here](https://github.com/neovim/node-client/issues/55)). Now running `:Up`again works without errors and after restarting the terminal the game works.
> 
> @gsihaj5 Hopefully this works for you too.

Also make sure you are using node 10.x.
`:Up` will not work with a older version of node

**Comment by gsihaj5** [comment]
i dont know what am i doin, but i try repeat the readme and it works :D

**Comment by Matthieu-OD** [comment]
Sorry to use a closed report but I have the same error `E492: Not an editor command: VimBeGood`.
Every thing else is ok and when I run `:Up` I have `remote/host: generated rplugin manifest: /Users/matthieuolenga/.local/share/nvim/rplugin.vim`
Somebody have an idea on how to resolve this ?

**Comment by FedeCuci** [comment]
Did you try running `sudo npm install -g neovim` in the command line and then run `:Up` again within neovim? It solved the issue for me. @Matthieu-OD

**Comment by Matthieu-OD** [comment]
I try your command but I still have the same thing with `:Up` (I don't even know if it's an error ...) and the error `E492: Not an editor command: VimBeGood` when I type `:VimBeGood` @FedeCuci

**Comment by Matthieu-OD** [comment]
I use this command `curl -sL install-node.now.sh/lts | bash` and I do other stuff (not to resolve this specific issue) and now it works ! Thanks for your help !

**Comment by kujbika** [comment]
I also face this issue, and I have run all the commands that were adviced.

**Comment by ThePrimeagen** [comment]
@kujbika Just to make sure, do you have the following? 

1. neovim
2. node
3. global install of neovim via npm (i know sucks.  considering going to lua for this).
4. `Plug 'ThePrimeagen/vim-be-good', {'do': './install.sh'}`
5. `:PlugInstall`
6. `:Up`
7. `:VimBeGood`
8. ...
9. Speed?

Also, can you put your `:checkhealth` output here?

**Comment by kujbika** [comment]
@ThePrimeagen 
I have everything up to point 6. Whenever I try to run :Up in nvim, I have:
 remote/host: generated rplugin manifest: /Users/matthieuolenga/.local/share/nvim/rplugin.vim
just as @Matthieu-OD did.
However, nothing seems to work to resolve that issue.

:checkhealth output:

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - ERROR: command failed: infocmp -L
    infocmp: couldn't open terminfo file /usr/share/terminfo/76/vtpcon.

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Python38\python.EXE is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Python38\python.EXE
  - INFO: Other python executable: C:/Python38/python
  - INFO: Other python executable: /python
  - INFO: Other python executable: C:/Users/User/AppData/Local/Programs/Python/Python38-32/python
  - INFO: Python version: 3.8.3
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
  - INFO: Host: C:\tools\ruby27\bin\neovim-ruby-host.bat
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v12.18.0
  - INFO: Neovim node.js host: C:\Users\User\AppData\Roaming\npm\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

**Comment by jonmwood** [comment]
I'm facing the same issue and have the same results/output as @kujbika

**Comment by kujbika** [comment]
We should reopen this issue, I guess

**Comment by ThePrimeagen** [comment]
@jonmwood perhaps we need to have a video call so I can see you do every step.  @kujbika it will be hard for me to help you at all, i not familiar with windows in any fashion other than C:\ is home from the 90s.

**Comment by kujbika** [comment]
@ThePrimeagen Anyways, if you come up with something, please share, it might help me (and other windows users) resolving the issue.

**Comment by ThePrimeagen** [comment]
@kujbika A primary motivator to move to Lua is to resolve this type of issue.  I am convinced that remote plugins have some dark corners that I don't understand.

**Comment by jonmwood** [comment]
> @jonmwood perhaps we need to have a video call so I can see you do every step.

With the latest update that I pulled down and I npm installed inside the vim-be-good directory and it worked!

**Comment by kujbika** [comment]
@ThePrimeagen I have to admit, that I messed up the installation process; I typed / instead of \ by accident in {'do': '.\install.sh'}. It took me an eternity to find this typo. After fixing this, the installation went smoothly, and the game works like a charm. 
Sorry for taking your time! 
From my part, the issue can be closed.

**Comment by ThePrimeagen** [comment]
ohh my life feels so much nicer.  I was getting genuinely worried about the usage of TS for a plugin.

**Comment by hqkhan** [comment]
Hi @ThePrimeagen, I wasn't sure if this is resolved or not because I'm still running into this issue. Here is my checkhealth output:

```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10ms
  - INFO: $TERM: st-256color
  - INFO: default-terminal: screen-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /home/hkhan/Work/SAILS/work_env/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - WARNING: Your virtualenv is not set up optimally.
    - ADVICE:
      - Create a virtualenv specifically for Neovim and use `g:python3_host_prog`.  This will avoid the need to install the pynvim module in each virtualenv.
  - INFO: $VIRTUAL_ENV matches executable
  - INFO: Executable: /home/hkhan/Work/SAILS/work_env/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.8.3
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v14.6.0
  - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
```

I went through the installation steps in order. I reinstalled it after the first time failed but still no dice.

**Comment by hqkhan** [comment]
No idea what I did but it's working now...

**Comment by ThePrimeagen** [comment]
@hqkhan I am going to be finishing up my Lua port hopefully soon (another 2 - 5 hours before I can have a games class that people can override).

**Comment by hqkhan** [comment]
Good to hear. Thanks for making this. They're already helpful in increasing my speed.
