### ISSUE TITLE
make a website out of this

### ISSUE THREAD

**Issue by devhindo** [ThePrimeagen/vim-be-good#133]
It would be cool for newbies to go ahead and play the game on a web page instead of going through the setup process

**Comment by brandoncc** [comment]
There are lots of websites already https://duckduckgo.com/?q=vim+learning+games&t=brave&ia=web

**Comment by brandoncc** [comment]
Oops, I didn't mean to close the issue.

**Comment by devhindo** [comment]
yeah sure
