### ISSUE TITLE
Floating/Popup buffer

### ISSUE THREAD

**Issue by bryall** [ThePrimeagen/vim-be-good#16]
Besides making sure the current buffer is empty, it would be nice to create a new buffer in the floating/popup buffer

**Comment by ThePrimeagen** [comment]
Yeah, I want to do that.  First nvim plugin makes that hard.  :)  

Still trying to create a window.  Based on CoC's implementation I need a VimL function to create an empty buffer then pass back the ids for my node application to attach to.

This is definitely something I want to do, just lower on the pri.

**Comment by ThePrimeagen** [comment]
addressed in #28 

Great work btw.

**Comment by ThePrimeagen** [comment]
H
