### ISSUE TITLE
Game doesn't start after deleting a line

### ISSUE THREAD

**Issue by kubami19** [ThePrimeagen/vim-be-good#18]
`:VimBeGood` command is working (I have vim installed through apt install as I'm on Ubuntu + I installed neovim globally through npm thinking it could maybe solve the problem) and I get the menu screen but after deleting an item nothing happens.

I installed plugin using Plug and I'm using NVIM v0.2.2

Preview with `:checkhealth`: https://asciinema.org/a/2h1f94vONvNqv4QrEfzt5SIuK

Anyone having a clue why it's not working?

**Comment by ThePrimeagen** [comment]
interesting.  Your nvim is _really_ old.  Would you be able to update to at least the 0.4x branch?

I don't think that is the issue, but its worth a try.  It looks like the game is _not_ picking up the change.

Tonight on stream I'll ensure we have a robust logging solution in place to be able to detect the issue.

There is also ways to get additional logging context (by setting a logging file) and I'll have that all prepared tomorrow for you if updating nvim does not work.

**Comment by ThePrimeagen** [comment]
Could you get the latest Vim-be-good and try again with debugging steps (found in readme, but here for convenience).

`NVIM_NODE_LOG_FILE=nvim.log nvim .`

This will give me console.log output and you could copy / paste out the logs.  Perhaps I can see something that is going wrong.

**Comment by kubami19** [comment]
I updated it to v0.4.3 and it helped, everything is working fine now :smile: 

I had no idea my nvim is so old. For anyone else on Ubuntu running on similar problem, I needed to add new PPA from [here](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu):

```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim
```

Thank you very much for help and such engagement in my problem. And for all the vim stuff you make of course, I greatly appreciate it :slightly_smiling_face:
