### ISSUE TITLE
[bug] arrow points on empty space in 'whackamole' game

### ISSUE THREAD

**Issue by alex-popov-tech** [ThePrimeagen/vim-be-good#27]
Thanks for the plugin!

Screenshot tells more about the error - https://share.getcloudapp.com/9Zujqlk8

**Comment by ThePrimeagen** [comment]
I believe I have fixed this. Would you be willing to update the plugin, you may have to uninstall it I am unsure, and see if you can reproduce the issue? I have yet to be able to reproduce the issue.

**Comment by ThePrimeagen** [comment]
I think I have addressed this. Reopen if I am wrong
