### ISSUE TITLE
[New feature] Endless practisce mode

### ISSUE THREAD

**Issue by FL3SH** [ThePrimeagen/vim-be-good#40]
I would like to have an option to disable timeouts and practice as long as I want regardless of my reaction time.

It would be nice if I could set `let g:vim_be_good_practice_mode = 1` or select such an option on the game menu.

**Comment by FL3SH** [comment]
I was thinking about sth similar to `g:vim_be_good_practice_mode_games`, but in my opinion, it is not necessary.

If you want to start practice mode you just set `g:vim_be_good_practice_mode` and it should bypass timeouts and other restrictions in all game types when you finish, you can flip this flag and use vim be good in 'normal' mode. Moreover, you could just set new remapping and easily flip this flag on the fly, it would be much easier and faster than with `ractice_mode_games` array.

**Comment by ThePrimeagen** [comment]
What do you think about instead of delete a line, you add a specific letter (p?) to any part of the line, and you go into practice version of the game.  Thoughts?

**Comment by FL3SH** [comment]
Would it be sth like `5jVp` [I guess `p` isn't a good choice in this case] instead of `5jVd` (for 5 lines below)?

What about the timeout, would it be ignored as well?

**Comment by lpanebr** [comment]
> What do you think about instead of delete a line, you add a specific letter (p?) to any part of the line, and you go into practice version of the game. Thoughts?

Very hacky isn't it?

What about having only one config option `A companion optional option could be an array g:vim_be_good_practice_mode_games = ['wacka']` and then a option to start training mode in the start screen?

This way one can have their preferred configured and use our not from the start screen without having to remember the insert p hack.

**Comment by ThePrimeagen** [comment]
The only thing I don't like about a flag is that it requires you to edit your vimrc to swap betwixt practice and game time.  I would prefer to find a solution that can do both!

There are 4 ways I can imagine doing this.  1.  mutate the line.  2.  Add a second list for practice 3.  Add a mode section where its Game Time or Practice.  4.  Add a vim rc option to turn on / off

I think I like option 3 the best

**Comment by lpanebr** [comment]
I think option 3 is what I (tried) to describe.

The config option is optional and only used if you want to train selected
games (if the random game changer is also developed).

>

**Comment by ThePrimeagen** [comment]
Ohh random is available, gotta update to latest :)

**Comment by FL3SH** [comment]
Mostly done by #60 .

**Comment by ThePrimeagen** [comment]
I think this is "considered" done.  I think `Noob` mode is the appropriate place to do endless mode.  You just play until you are done.

But I do think 10 rounds should be rethought.  Perhaps some sort of "endurance" setting.

**Comment by FL3SH** [comment]
I am not so happy with it, I can play but I don't know my score and how far I am. 
It needs a few improvements.

>  I think `Noob` mode is the appropriate place to do endless mode. You just play until you are done.
You can play until you learn it or die ;)
