### ISSUE TITLE
Refactor src/index.ts

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/vim-be-good#46]
Its clear from about 10 days ago that that file sucks.  It sucks in every way.

I like where Game and GameBuffer are going.  I think they could use a bit more utility.  But there appears to be something else that needs to be created.  Some sort of runner that runs the game itself.  This will allow for a couple things.

1.  index.ts will consist of scaffolding.  No real logic within it.
2.  It will allow for what takes its place to be testable.  The current setup just sucks.  SUCKS.  
3.  Have I said I hate that file enough yet?   Sorry not Sorry.

Thank you.

PS.  I really hate that file.

**Comment by bryall** [comment]
closing since we switched to lua
