### ISSUE TITLE
Untimed Noob-Mode

### ISSUE THREAD

**Issue by Roni1993** [ThePrimeagen/vim-be-good#58]
Hey there,

at the moment im kinda overwhelmed with the speed of all the games other then 'hjkl' but i also have not used vim a my main editor. I tried 'vim-be-good' and i really like the idea. The only thing is that for me the speed of the refresh is to fast.

Would it be possible to add a "untimed" mode for noobs where yo can take your time to think of the proper vim movement and execute it "in peace"?

**Comment by ThePrimeagen** [comment]
This is a great idea!

I'll do this once I get back on working on this (later this week is my assumption).

**Comment by lramo062** [comment]
https://github.com/ThePrimeagen/vim-be-good/pull/59

**Comment by ThePrimeagen** [comment]
@Roni1993 feel free to update and receive `noob` mode, complete with no timer :)

**Comment by Roni1993** [comment]
Seems to be working fine :), TY!
Now im able to fail slowly :D

**Comment by brandoncc** [comment]
@Roni1993 noob mode also never runs out of rounds anymore :-)

**Comment by Roni1993** [comment]
@brandoncc the endless mode is awesome. just had the time to test the modified noob mode.
Now I'm able to do 10 min sessions at once. 👍

**Comment by brandoncc** [comment]
@Roni1993 you can thank @FL3SH for that. I was involve as a code reviewer, but they wrote all the code. 😄

I'm glad you like it!
