### ISSUE TITLE
Error while handling line: nvim_buf_set_lines: Index out of bounds

### ISSUE THREAD

**Issue by IgnacyWie** [ThePrimeagen/vim-be-good#69]
The game doesn't count the actions I made and I cannot rich the end and score.

**Comment by FL3SH** [comment]
I guess you are in the practice mode. 
Just don't select the 'noob' difficult and you should be good.

**Comment by ThePrimeagen** [comment]
Yes you are in noob mode.  It will continue on for ever.

**Comment by ThePrimeagen** [comment]
I'll make it so that easy is the default difficulty selected.  This will prevent this confusion from happening.
