### ISSUE TITLE
Install with dein

### ISSUE THREAD

**Issue by nexusstar** [ThePrimeagen/vim-be-good#76]
I am using [dein.vim](https://github.com/Shougo/dein.vim) as plugin manager 
but am unable to start vim-be-good after installing it with it
for installing I am using the following line:
```sh
call dein#add('ThePrimeagen/vim-be-good')
```
And I see that it's installed but the command `VimBeGood` is not recognized after the install.
I am not so sure how to debug this so will be glad if someone has any ideas or pointers.

**Comment by TamaMcGlinn** [comment]
I have the exact same issue. You can start debugging with `checkHealth` - check that you have nodejs support. In my case, I needed to do some steps for that. But afterwards, it still won't recognize the VimBeGood command.

**Comment by TamaMcGlinn** [comment]
I see there is an install.sh script which uses npm to install something. Could you this as your 'add plugin' part?

```
call dein#add('ThePrimeagen/vim-be-good', {
    \ 'build': './install' 
    \ })
```

In my case, going into ~/vimscripts/dein/repos/github.com/ThePrimeagen/vim-be-good and executing install.sh worked, but the above should do that just as well.

**Comment by brandoncc** [comment]
@TamaMcGlinn nothing is installed actually. [Setup scripts](https://github.com/ThePrimeagen/vim-be-good/blob/master/package.json#L7-L8) are run, which setup the rplugin directory that neovim needs.

**Comment by ThePrimeagen** [comment]
@nexusstar I am just about to finish the Lua rewrite which should solve all these issues.  Sorry about this.

**Comment by ThePrimeagen** [comment]
Btw, the Lua rewrite has been out there for some time.  Check it out.

btw, read the instructions, they have changed significantly, and there are more options.

**Comment by bryall** [comment]
lua refactor should resolve this issue
