### ISSUE TITLE
invalid method: nvim_create_buf 

### ISSUE THREAD

**Issue by TamaMcGlinn** [ThePrimeagen/vim-be-good#78]
After installing, when I run `VimBeGood` I get the following message:

```
Error: nvim_create_buf: Invalid method: nvim_create_buf
```

I am guessing that means you need at least Neovim version X. I am on 0.3.2.

**Comment by brandoncc** [comment]
That method was added in a [commit](https://github.com/neovim/neovim/commit/891ed14f13c3ea99d3fb985371c69f769ee7ff57) to neovim on Feb 9, 2019. The first version cut after that was 0.3.5. Hope this helps.

**Comment by n0thing2speak** [comment]
Neovim version 0.3.8 still has this problem

**Comment by brandoncc** [comment]
I guess the commit must not have been in master when 0.3.5 was cut. I'm not sure when it was added then, without digging through the git history some more.

**Comment by TamaMcGlinn** [comment]
Neovim 0.4.0 mentions this in the release notes; you should state that as your minimum neovim version in the readme.
