### ISSUE TITLE
Quick way to restart

### ISSUE THREAD

**Issue by fsmiamoto** [ThePrimeagen/vim-be-good#8]
Is there already a way to quickly restart the game? 

Since this is for getting those Vim muscles trained up, I think it's crucial to have an easy way to just restart.

Maybe we could allow for `!` in the command to ignore a file that is not empty and just get back to action.

Thanks for the awesome work :v:

**Comment by ThePrimeagen** [comment]
That's a great idea. I'll do that next time I stream and work on this. Right now it's all deno.

**Comment by lpanebr** [comment]
I also like this!

**How about something like this?**
```
Success: 7 / 10 Average Success Time!: 2916.75
When you see a "DELETE ME", relative jump to it
as fast as possible and delete it.

What now? (delete from the list to select)
------------------------------------------
[X] retry
[ ] try a different game
[ ] go bak to work (clears the buffer)
```

**Comment by fsmiamoto** [comment]
@lpanebr Looks awesome! +1 for something like this

**Comment by FedeCuci** [comment]
For now you could make a keybinding which brings you back to the main menu. This is what I set in my `init.vim`:

`nnoremap <Leader>r ggdG:VimBeGood<CR> `

Now by simply pressing `Leader + r` brings me back to the main menu.

**Comment by ThePrimeagen** [comment]
Partially addressed with #28 
This will allow for a popup to be used.  What do you all think?  
I am going to add an option for this.

**Comment by deeperlearner** [comment]
> For now you could make a keybinding which brings you back to the main menu. This is what I set in my `init.vim`:
> 
> `nnoremap <Leader>r ggdG:VimBeGood<CR> `
> 
> Now by simply pressing `Leader + r` brings me back to the main menu.

This will casue that recursively open :VimBeGood.
So I think
`nnoremap <Leader>r :q<CR>:VimBeGood<CR>`
would be better.

**Comment by FedeCuci** [comment]
I haven't thought about that as I had no problems with my key bind by your is definitely a better approach :) @deeperlearner

**Comment by fsmiamoto** [comment]
Closing the issue since we now have a way to quickly restart!
```
Where do you want to go next? (Delete Line)
Menu
Replay
Quit (or just ZZ like a real man)
```
