### ISSUE TITLE
New command or something ...

### ISSUE THREAD

**Issue by OrangeFran** [ThePrimeagen/vim-be-good#80]
I actually typed in :VimBeGod yesterday and it got me thinking. A new command like VimBeGod would be pretty cool.
It could start in a new ultra-hard difficulty, which only "Gods" could beat. If you do beat it, your name goes into a hall of fame section in the readme.

Just an idea. I really like the plugin btw.

**Comment by ThePrimeagen** [comment]
ty ty!  I have recently redid this plugin into lua, so my guess is that the lua port has helped
