### ISSUE TITLE
Error:  nvim_create_buf: Invalid method: nvim_create_buf                                                              

### ISSUE THREAD

**Issue by n0thing2speak** [ThePrimeagen/vim-be-good#83]
Neovim version is 0.3.8 
#78 did not solve it
It drive me crazy for allllllllllllllllllllllllllllllday

**Comment by ThePrimeagen** [comment]
Interesting.  You should be on latest 4.x branch.  

Also I am rewritting this to be on NeoVim 5.x (currently build your own / downloading artifact required).  But it requires no more of this remote plugin nonsense.

Does that help?

**Comment by n0thing2speak** [comment]
> Interesting. You should be on latest 4.x branch.
> 
> Also I am rewritting this to be on NeoVim 5.x (currently build your own / downloading artifact required). But it requires no more of this remote plugin nonsense.
> 
> Does that help?

thanks for reply, it works when upgrade neovim to 0.4.3
