### ISSUE TITLE
Port a game for me?

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/vim-be-good#86]
@brandoncc or polarmutex (what was your github name????)

Could you consider porting one game for me?  Just to try it out and see how it goes?

After that, the lua lua branch can  become master and all those shitty install instructions can go away.

**Comment by brandoncc** [comment]
Considered and accepted :-)

**Comment by bryall** [comment]
Will do

**Comment by brandoncc** [comment]
So, I have been trying to get a lua lsp running on my mac for two hours with no luck. I'm not sure if I am going to be any help here after all.

**Comment by brandoncc** [comment]
I think I got it working, now I just have to learn lua 😂

**Comment by brandoncc** [comment]
Sorry to spam the thread....can I get some pointers on how to run the game? I understand the lua syntax so I think I am okay there, but I can't figure out how to execute anything!

**Comment by brandoncc** [comment]
Just so we don't work on the same game, I have made good progress on ci. Hopefully I will complete it tomorrow.

**Comment by bryall** [comment]
i am going to work on hjkl

**Comment by bryall** [comment]
> Sorry to spam the thread....can I get some pointers on how to run the game? I understand the lua syntax so I think I am okay there, but I can't figure out how to execute anything!
> 
> EDIT:
> 
> I figured out how to do it by running the following, let me know if I am doing anything wrong...
> 
> ```
> :set rtp^=~/dev/vim-be-good/
> :so ~/dev/vim-be-good/plugin/vim-be-good.vim
> ```

i run the game by ":call VimBeGood()" (assuming plugin is in the plugin path)

**Comment by ThePrimeagen** [comment]
Ohh my goodness!  I am sorry that I didn't respond.  Sleeping the kiddos.

Yes, I always use `nvim --cmd "set rtp+=$(pwd)" .` to start up vim when working on this branch.
`:call VimBeGood()` is the way to activate the lua version.  Why?  That way you can still have `vim-be-good` installed without having them collide.

To override a game @bryall and @brandoncc look at relative.lua.  Relative is the relative jumping game.  I tried to provide as many of the same tools out of the box.  The big difference is that a "round" provides a config every round, that means you can keep state if you would like and make it adaptively hard.  But, that perhaps, is 2.0.

@bryall For hjkl, it would be awesome if difficulty also increased the size of the hjkl board, that way you really had to get use to using hjkl to move around.

@brandoncc I just assumed you are doing whack-a-brandon ;)  One request, make the cursor position random on the line too, therefore more f and F is used. ;)

**Comment by ThePrimeagen** [comment]
One last thing, execute `:echo stdpath('data')` to see where the log is being written to.  THat way you can just tail -f it or you can enable console logging in log.lua (not the biggest fan of the `:messages` experience).

**Comment by bryall** [comment]
is there a command to reload a lua plugin while in neovim?

**Comment by brandoncc** [comment]
@bryall `:call VimBeGood()` does that for you. It sets the required `vim-be-good` packages to `nil`, then it requires it again. Check it out in plugin/vim-be-good.vim.

**Comment by bryall** [comment]
added PR for whackamole, i think that is all the games?

**Comment by brandoncc** [comment]
I saw that, nice job @bryall!
