### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by mickeypash** [ThePrimeagen/vim-be-good#98]
Having a docker image will allow for more portability.
Folks won't have to install `neovim` if they are coming from OG vim.
No globally installed `npm` Packages!

I found [this docker image for `neovim`](https://github.com/nicodebo/neovim-docker) which might a good starting point.
We can strip it down to the bare necessities and add `VimBeGood` on top.

**Comment by FL3SH** [comment]
I think this issue is no longer valid because now vim-be-good is written in Lua.

**Comment by brandoncc** [comment]
@FL3SH this is still valid, since the game requires users to build neovim master from source. Using docker removes that requirement.

**Comment by brandoncc** [comment]
I created this and opened #99.

**Comment by ThePrimeagen** [comment]
I am finishing up VimConf's talk, so I am going to be busy this weekend.  Will look at everything related to this on monday!  @brandoncc , if you say its good, i'll merge it.

**Comment by brandoncc** [comment]
@mickeypash take a look at the readme, this has been merged.

**Comment by mickeypash** [comment]
Great work! I've tested it and it works as expected. Closing this issue for now!
